//blog with users
GET http://localhost:3001/api/blogs
Content-Type: application/json
####
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "RecFanJia",
  "password": "2301335"
}

####
# 创建一个新的博客
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJlY0ZhbkppYSIsImlkIjoiNjY0NGI0NDBhN2IyZmZiMWFkZDAwMGVjIiwiaWF0IjoxNzE1ODc5NTY3fQ.RBeJWe3iaP5zGP7WyLChVnRfWyCDy1PZSJBo3KTgi3U

{
  "title": "Blog 44",
  "author": "Li Bai4",
  "url": "http://Libai4.com"
}

####
# 删除博客
DELETE http://localhost:3001/api/blogs/66450897e548af1aff6f54cb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJlY0ZhbkppYSIsImlkIjoiNjY0NGI0NDBhN2IyZmZiMWFkZDAwMGVjIiwiaWF0IjoxNzE1ODc5NTY3fQ.RBeJWe3iaP5zGP7WyLChVnRfWyCDy1PZSJBo3KTgi3U