//Blogs
GET http://localhost:3001/api/blogs
Content-Type: application/json
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/blogs/66409bf59cf433cfddc889fb
###
DELETE http://localhost:3001/api/blogs/6640a99b9afa0c49c2e15dc4

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Blog 2",
  "author": "FJ",
  "url": "http://example2.com",
  "likes": 55,
  "user": "6644b440a7b2ffb1add000ec"
}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJlY0xpc2h1byIsImlkIjoiNjY0NGI5MTg3ZmRmNzQ5YzM1MmU1ZmNmIiwiaWF0IjoxNzE1Nzg4NTgxfQ.FXikfXxMQRf-PYLOoWz6E49EMfYgLR8okhsJ15J1O1U"

{
  "title": "Blog 1",
  "author": "LS",
  "url": "http://example1.com",
  "likes": 5,
  "user": "6644b9187fdf749c352e5fcf"
}


//PUT http://localhost:3001/api/persons/663c8f5aae3a26be268a7559
//Content-Type: application/json
//
//{
//
//"number": "123456"
//}
