//blog with users
####
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "RecFanJia",
  "password": "2301335"
}




####
# 创建一个新的博客
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlJlY0ZhbkppYSIsImlkIjoiNjY0NGI0NDBhN2IyZmZiMWFkZDAwMGVjIiwiaWF0IjoxNzE1NzkwNDIxfQ.YYkpALg_ShLaquGJyv0Vx1GC_6HEVMuPk6fb_E1AKbM

{
  "title": "My New Blog",
  "author": "John Doe",
  "url": "http://example.com",
  "likes": 10
}