//Blogs
GET http://localhost:3001/api/blogs
Content-Type: application/json
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/blogs/66409bf59cf433cfddc889fb
###
DELETE http://localhost:3001/api/blogs/6640a99b9afa0c49c2e15dc4

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Blog 2",
  "author": "FJ",
  "url": "http://example2.com",
  "likes": 55,
  "user": "6644b440a7b2ffb1add000ec"
}
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Blog 1",
  "author": "LS",
  "url": "http://example1.com",
  "likes": 5,
  "user": "6644b9187fdf749c352e5fcf"
}
//blog with users
###
GET http://localhost:3001/api/users
Content-Type: application/json
###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "RecFanJia",
  "name": "FanJia",
  "password": "2301335"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "RecLishuo",
  "name": "Lishuo",
  "password": "2301335"
}
###
PUT http://localhost:3001/api/users/RecFanJia
Content-Type: application/json

{
  "name": "FanJia Updated",
  "password": "newpassword123"
}

###

DELETE http://localhost:3001/api/users/RecFanJia
Content-Type: application/json

//PUT http://localhost:3001/api/persons/663c8f5aae3a26be268a7559
//Content-Type: application/json
//
//{
//
//"number": "123456"
//}
